### read all

GET localhost:3000/api/cards/1
Accept: application/json

### read one

GET localhost:3000/api/cards/1/1
Accept: application/json

### create

POST localhost:3000/api/cards/1
Content-Type: application/x-www-form-urlencoded

from_text = One &
to_text_primary = Un

### update

PUT localhost:3000/api/cards/1/560
Content-Type: application/x-www-form-urlencoded

rating = 42

### delete

DELETE localhost:3000/api/cards/1/1
Content-Type: application/json
