### read all

GET localhost:3000/api/decks
Accept: application/json

### read one

GET localhost:3000/api/decks/1
Accept: application/json

### create

POST localhost:3000/api/decks
Content-Type: application/x-www-form-urlencoded

from_language = AI &
to_language = Human

### update

PUT localhost:3000/api/decks/2
Content-Type: application/x-www-form-urlencoded

email = simon@gmail.com

### delete

DELETE localhost:3000/api/decks/2
Content-Type: application/json
