### read all

GET localhost:3000/api/users
Accept: application/json

### read one

GET localhost:3000/api/users/1
Accept: application/json

### create

POST localhost:3000/api/users
Content-Type: application/json

{
    "name": "Glen",
    "first": "Volker",
    "last": "Project",
    "email": "volker@project.com"
}

### update

PUT localhost:3000/api/users
Content-Type: application/json

{
    "id": 5,
    "name": "Birgitt",
    "first": "Glen",
    "last": "Coden"
}

### delete

DELETE localhost:3000/api/users/5
Content-Type: application/json
